project:
  type: website

website:
  title: "Munich public Toilets"
  navbar:
    left:
      - href: index.qmd
        text: Home


      - href: wcproject.qmd
        text: Analysis

      - href: group-reflection.qmd
        text: Group Reflection


format:
  html:
    theme: cosmo
    toc: true
execute:
  echo: false
  warning: false
  message: false
